# Generated by Django 3.1.7 on 2022-02-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigoArticulo', models.CharField(max_length=7)),
                ('nombreArticulo', models.CharField(max_length=50)),
                ('descripcionArticulo', models.CharField(max_length=200)),
                ('cantidadArticulo', models.IntegerField()),
            ],
        ),
    ]
